post:
  x-last-updated-at: 2024.12.05
  x-role:
    - 服务商
    - 电商平台
  tags:
    - 基础支付∙服务商模式
    - 收付通∙支付
  summary: APP下单API
  description: 商户系统先调用该接口在微信支付服务后台生成预支付交易单，返回正确的预支付交易会话标识后再在APP里面调起支付。 [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter5_1.shtml) [官方文档](https://pay.weixin.qq.com/doc/v3/partner/4012523526)
  parameters:
    - $ref: '../../../../definitions/Parameters.yaml#/HTTP_WECHATPAY_SERIAL'
    - name: _
      in: body
      required: true
      schema:
        allOf:
          - $ref: '../../../../definitions/Transaction.yaml#TransactionServiceProvider'
          - $ref: '../../../../definitions/Transaction.yaml#TransactionBase'
          - type: object
            properties:
              payer:
                type: object
                description: 支付者
                properties:
                  identity:
                    type: object
                    description: 实名支付(需单独申请权限)
                    required:
                      - type
                      - number
                      - name
                    properties:
                      type:
                        type: string
                        description: 证件类型
                        enum:
                          - IDCARD
                          - HONGKONG_MACAO
                          - HONGKONG_MACAO_RESIDENT
                          - TAIWAN_RESIDENT
                          - FOREIGN_RESIDENT
                          - OVERSEA_PASSPORT
                      number:
                        type: string
                        format: base64
                        description: 加密后的证件号
                        example: 6B46824C852FA29AAC3DCE6BFD852E27
                      name:
                        type: string
                        format: base64
                        description: 加密后的姓名
                        example: 6B46824C852FA29AAC3DCE6BFD852E27
          - type: object
            properties:
              subsidy_info:
                type: object
                description: 贴息信息(微信分付)
                properties:
                  subsidy_detail:
                    type: array
                    description: 贴息详情列表
                    items:
                      type: object
                      required:
                        - subsidy_period_type
                        - subsidy_plan
                      properties:
                        subsidy_period_type:
                          type: string
                          description: 贴息方案类型
                          example: PERIOD
                          enum:
                            - DAILY  #随时还
                            - PERIOD #分期还
                        subsidy_plan:
                          type: array
                          description: 贴息方案列表
                          items:
                            type: object
                            required:
                              - subsidy_installment_num
                              - subsidy_percent
                            properties:
                              subsidy_installment_num:
                                type: integer
                                description: 贴息期数
                                example: 3
                                enum:
                                  - 3
                                  - 6
                                  - 12
                              subsidy_percent:
                                type: integer
                                description: 贴息比例
                                example: 100
                                enum:
                                  - 0
                                  - 100
  responses:
    200:
      schema:
        type: object
        required:
          - prepay_id
        properties:
          prepay_id:
            type: string
            description: 预支付交易会话标识
            example: wx201410272009395522657a690389285100
