post:
  x-last-updated-at: 2025.08.14
  x-role:
    - 电商平台
  tags:
    - 收付通∙个人收款
  summary: APP场景预签约
  description: 商户可调用本接口预先指定签约，生成预签约会话及对应的预签约ID，再携带预签约ID（pre_entrustweb_id）参数，通过微信SDK拉起微信支付客户端的签约页面。
  parameters:
    - name: _
      in: body
      required: true
      schema:
        type: object
        required:
          - sub_mchid
          - agreement_list
        properties:
          appid:
            type: string
            description: 签约和付款的AppID
            example: wxd678efh567h23787
          out_contract_code:
            type: string
            description: 业务申请单号
            example: APPLYMENT_00000000001
  responses:
    '200':
      schema:
        type: object
        required:
          - pre_entrustweb_id
        properties:
          pre_entrustweb_id:
            type: string
            description: 预签约id
            example: 1121_9f3cec22a2d367737674d08d98e5e07b8388495fafedc0eba83c327e8ad720ed_12bfdd59b387c4bff8543de4719a886a
