post:
  x-version: [V1.1, 2020.11.12]
  x-role:
    - 服务商
    - 电商平台
  tags:
    - 基础支付∙普通支付∙服务商模式
    - 电商收付通∙普通支付
  summary: APP下单API
  description: 商户系统先调用该接口在微信支付服务后台生成预支付交易单，返回正确的预支付交易会话标识后再在APP里面调起支付。 [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/pay/transactions/chapter5_1.shtml)
  parameters:
    - name: _
      in: body
      required: true
      schema:
        allOf:
          - $ref: '../../../../definitions/Transaction.yaml#TransactionServiceProvider'
          - $ref: '../../../../definitions/Transaction.yaml#TransactionBase'
  responses:
    200:
      schema:
        type: object
        required:
          - prepay_id
        properties:
          prepay_id:
            type: string
            description: 预支付交易会话标识
            example: wx201410272009395522657a690389285100
