post:
  x-version:
    - 2023.12.05
  x-role:
    - 机构模式
  tags:
    - 跨境∙H5权限
  summary: 创建H5支付域名修改申请单
  description: 商户可以通过该接口为自身和子商户发起H5支付域名修改申请。 [官方文档](https://pay.weixin.qq.com/wiki/doc/api_external/ch/apis/chapter4_4_4.shtml)
  parameters:
    - name: _
      in: body
      required: true
      schema:
        type: object
        required:
          - domains
          - website_url
          - out_applyment_id
        properties:
          sub_mchid:
            type: string
            description: 子商户号
            example: '2491935631'
          domains:
            type: array
            items:
              type: string
              description: 域名
            description: H5支付域名
            example: ["qq.com"]
          website_url:
            type: string
            description: 子商户H5经营网址
            example: https://qq.com
          website_business_page_pics:
            type: array
            items:
              type: string
              format: MediaId
              description: 图片MediaID
            description: 经营网址商业页面截图
            example: ["6uqyGjvHzOhsLleGFQVRF"]
          website_homepage_pics:
            type: array
            items:
              type: string
              format: MediaId
              description: 图片MediaID
            description: 经营网址首页截图
            example: ["6uqyGjvHzOhsLleGFQVRF"]
          website_state:
            type: string
            description: 子商户经营网址状态
            example: HAS_LAUNCHED
            enum:
              - HAS_LAUNCHED
              - UN_LAUNCHED
          notify_url:
            type: string
            description: 商户提供的审核结果回调接口
            example: https://pay.weixin.qq.com/wxpay/pay.action
          out_applyment_id:
            type: string
            description: 商户申请单号
            example: '123456'
  responses:
    '200':
      schema:
        type: object
        required:
          - sub_mchid
          - website_state
          - domains
          - webiste_url
          - applyment_id
          - out_applyment_id
        properties:
          sub_mchid:
            type: string
            description: 子商户号
            example: '2491935631'
          website_state:
            type: string
            description: 子商户经营网址状态
            example: HAS_LAUNCHED
            enum:
              - HAS_LAUNCHED
              - UN_LAUNCHED
          domains:
            type: array
            items:
              type: string
              description: 域名
            description: H5支付域名
            example: ["qq.com"]
          webiste_url:
            type: string
            description: 子商户H5经营网址
            example: https://qq.com
          website_business_page_pics:
            type: array
            items:
              type: string
              format: MediaId
              description: 图片MediaID
            description: 经营网址商业页面截图
            example: ["6uqyGjvHzOhsLleGFQVRF"]
          website_homepage_pics:
            type: array
            items:
              type: string
              format: MediaId
              description: 图片MediaID
            description: 经营网址首页截图
            example: ["6uqyGjvHzOhsLleGFQVRF"]
          applyment_id:
            type: integer
            description: 申请单号
            example: 1000000
          audit_reject_detail:
            type: string
            description: 驳回原因
            example: 经营网址首页截图内容违法
          applyment_state:
            type: string
            description: 申请单状态
            example: PENDING
            enum:
              - PENDING
              - UNDER_REVIEW
              - APPROVED
              - REJECTED
          notify_url:
            type: string
            description: 商户提供的审核结果回调接口
            example: https://pay.weixin.qq.com/wxpay/pay.action
          out_applyment_id:
            type: string
            description: 商户申请单号
            example: '123456'
