# 对于上行有敏感信息的请求，需要设置此头参数
WECHATPAY_CERTIFICATE_SERIAL:
  in: header
  required: true
  name: Wechatpay-Serial
  description: 平台公钥ID/平台公钥证书序列号
  example: PUB_KEY_ID_0114232134912410000000000000
HTTP_ACCEPT_ENCODING:
  in: header
  name: Accept-Encoding
  description: 账单压缩：如需对账单进行压缩，设置HTTP请求头值为gzip
  example: gzip
HTTP_IDEMPOTENCY_KEY:
  in: header
  name: Idempotency-Key
  description: 由商户侧生成的唯一key，用来标识多次重试是否为同一请求
  example: GzPCeo963zXKcO2hDVD8AjXIpgrj
  maxLength: 64
