querysubdevconfig.request:
  allOf:
    - type: object
      xml:
        name: xml
      required:
        - appid
        - mch_id
        - sub_mch_id
        - sign
      properties:
        appid:
          type: string
          description: 公众账号ID
          example: wx8888888888888888
          maxLength: 32
        mch_id:
          type: string
          description: 商户号
          example: '1900000109'
          maxLength: 32
        sub_mch_id:
          type: string
          description: 子商户号
          example: '1900000100'
          maxLength: 32
        sign:
          type: string
          description: 签名
          example: C380BEC2BFD727A4B6845133519F3AD6
          maxLength: 32
querysubdevconfig.response:
  allOf:
    - type: object
      xml:
        name: xml
      required:
        - return_code
        - return_msg
      properties:
        return_code:
          type: string
          description: 返回状态码
          example: SUCCESS
          maxLength: 16
          enum:
            - SUCCESS
            - FAIL
        return_msg:
          type: string
          description: 返回信息
          example: OK
          maxLength: 128
    - type: object
      xml:
        name: xml
      required:
        - err_code
        - err_code_des
      properties:
        err_code:
          type: string
          description: 错误代码
          example: INVALID_REQUEST
          maxLength: 32
        err_code_des:
          type: string
          description: 错误代码描述
          example: 子商户号信息有误，请检查修改后重试
          maxLength: 128
    - type: object
      xml:
        name: xml
      required:
        - sign
        - result_code
        - jsapi_path_list
        - appid_config_list
      properties:
        result_code:
          type: string
          description: 业务结果
          example: SUCCESS
          maxLength: 32
          enum:
            - SUCCESS
            - FAIL
        sign:
          type: string
          description: 签名
          example: C380BEC2BFD727A4B6845133519F3AD6
          maxLength: 32
        jsapi_path_list:
          xml:
            x-cdata: true
          type: string
          format: jsonObjectLike
          description: 授权目录
          example: '{"jsapi_path_list":["http://www.qq.com/abcd/","http://www.qq.com/abcdedfg/"]}'
          maxLength: 2048
          x-json:
            type: object
            properties:
              jsapi_path_list:
                type: array
                description: 支付目录URI数组
                items:
                  type: string
                  description: 支付目录URI
        appid_config_list:
          xml:
            x-cdata: true
          type: string
          format: jsonObjectLike
          description: 关联APPID与关注特约商户公众号的APPID
          example: '{"appid_config_list":[{"subscribe_appid":"wxa9d9651ae82ec4b9","sub_appid":"null"},{"subscribe_appid":"wxa9d9651ae82ec4b9","sub_appid":"wxa9d9651ae82ec4b9"}]}'
          maxLength: 1024
          x-json:
            type: object
            properties:
              appid_config_list:
                type: array
                description: 关联与关注APPID数组
                items:
                  type: object
                  description: APPID数组
                  properties:
                    subscribe_appid:
                      type: string
                      description: 关注特约商户公众号的APPID
                    sub_appid:
                      type: string
                      description: 绑定好的商户公众号、小程序、APP支付等APPID
