get:
  x-last-updated-at: 2026.01.29
  x-role:
    - 服务商
  tags:
    - 经营工具∙品牌入驻
  summary: 获得品牌已授权且在生效中的产品权限信息
  description: 获得品牌已授权且在生效中的产品权限信息
  parameters:
    - name: brand_id
      in: path
      required: true
      type: string
      description: 品牌ID
      example: '123456789'
  responses:
    '200':
      schema:
        type: object
        required:
          - brand_id
          - authorization_type
          - update_time
        properties:
          brand_id:
            type: string
            description: 品牌ID
            example: '123456789'
          authorization_type:
            type: string
            description: 授权类型
            example: AUTHORIZATION_TYPE_HOSTING
            enum:
              - AUTHORIZATION_TYPE_HOSTING
              - AUTHORIZATION_TYPE_PARTLY
          authorization_product:
            description: 授权产品权限
            type: array
            items:
              type: string
              enum:
                - BRAND_PRODUCT_AUTHORITY_MERCHANT_CARD
                - BRAND_PRODUCT_AUTHORITY_CARD_LINK
                - BRAND_PRODUCT_AUTHORITY_PRODUCT_COUPON
                - BRAND_PRODUCT_AUTHORITY_SHAKE_COUPON
                - BRAND_PRODUCT_AUTHORITY_BRAND_PAY_GIFT
                - BRAND_PRODUCT_AUTHORITY_BRAND_STORE
                - BRAND_PRODUCT_AUTHORITY_PAYMENT_MERCHANT_MANAGE
                - BRAND_PRODUCT_AUTHORITY_APPID_MANAGE
                - BRAND_PRODUCT_AUTHORITY_FINDER_MANAGE
                - BRAND_PRODUCT_AUTHORITY_CATEGORY_MANAGE
          update_time:
            type: string
            format: rfc3339
            description: 更新时间
            example: '2025-05-20T13:29:35+08:00'
