<?php declare(strict_types=1);/* Generated file. DO NOT EDIT! */

namespace WeChatPay\OpenAPI\V3\Gov\Subsidy\Audit\Cup;

use Psr\Http\Message\ResponseInterface;
use GuzzleHttp\Promise\PromiseInterface;

/**
 */
interface Upload
{
    /**
     * 上传审核数据(同步模式)
     * @param array<string,mixed> $options
     * @link https://wechatpay.im/openapi/v3/gov/subsidy/audit/cup/upload
     */
    public function post(array $options = [
        'json' => [
            'org_no' => '',
            'sub_mchnt_cd' => '',
            'sub_mchnt_nm' => '',
            'store_nm' => '',
            'online_no' => '',
            'mchnt_order_id' => '',
            'upload_time' => '',
            'notify_url' => '',
            'prod_id' => '',
            'eng_grade' => '',
            'brand_nm' => '',
            'prod_model' => '',
            'sales_chnl' => '',
            'plat_form' => '',
            'payer_tp' => '',
            'trade_in_order_id' => '',
            'trade_in_at' => '',
            'is_trade_in' => '',
            'sales_at' => '',
            'actual_at' => '',
            'trans_tm' => '',
            'mchnt_cd' => '',
            'mer_sub_at' => '',
            'discount_at' => '',
            'image01' => '',
            'image02' => '',
            'image03' => '',
            'image04' => '',
            'image05' => '',
            'image06' => '',
            'image07' => '',
            'image08' => '',
            'image09' => '',
            'image10' => '',
            'commitment_letter_photo' => '',
            'commitment_letter_photo_format' => '',
            'device_photo' => '',
            'device_photo_format' => '',
            'pack_and_active_photo' => '',
            'bar_code' => '',
            'sn_code' => '',
            'imei1' => '',
            'imei2' => '',
            'register_model' => '',
            'record_number' => '',
            'eng_grade_standard' => '',
            'invoice_info' => [
                'invoice_cd' => '',
                'invoice_no' => '',
                'invoice_dt' => '',
                'invoice_link' => '',
                'invoice_tp' => '',
                'invoice_ck_cd' => '',
                'nm' => '',
                'tax' => '',
                'invoice_tax_amt' => '',
                'sales_ent_nm' => '',
                'tax_payer' => '',
                'num' => '',
                'service_nm' => '',
            ],
            'track_info' => [
                'tracking_no' => '',
                'tracking_company' => '',
                'usr_prov' => '',
                'usr_city' => '',
                'usr_area' => '',
                'usr_addr' => '',
                'tracking_type' => '',
                'delivery_method' => '',
                'shipping_addr' => '',
                'delivery_time' => '',
            ],
        ],
    ]): ResponseInterface;

    /**
     * 上传审核数据(异步模式)
     * @param array<string,mixed> $options
     * @link https://wechatpay.im/openapi/v3/gov/subsidy/audit/cup/upload
     */
    public function postAsync(array $options = [
        'json' => [
            'org_no' => '',
            'sub_mchnt_cd' => '',
            'sub_mchnt_nm' => '',
            'store_nm' => '',
            'online_no' => '',
            'mchnt_order_id' => '',
            'upload_time' => '',
            'notify_url' => '',
            'prod_id' => '',
            'eng_grade' => '',
            'brand_nm' => '',
            'prod_model' => '',
            'sales_chnl' => '',
            'plat_form' => '',
            'payer_tp' => '',
            'trade_in_order_id' => '',
            'trade_in_at' => '',
            'is_trade_in' => '',
            'sales_at' => '',
            'actual_at' => '',
            'trans_tm' => '',
            'mchnt_cd' => '',
            'mer_sub_at' => '',
            'discount_at' => '',
            'image01' => '',
            'image02' => '',
            'image03' => '',
            'image04' => '',
            'image05' => '',
            'image06' => '',
            'image07' => '',
            'image08' => '',
            'image09' => '',
            'image10' => '',
            'commitment_letter_photo' => '',
            'commitment_letter_photo_format' => '',
            'device_photo' => '',
            'device_photo_format' => '',
            'pack_and_active_photo' => '',
            'bar_code' => '',
            'sn_code' => '',
            'imei1' => '',
            'imei2' => '',
            'register_model' => '',
            'record_number' => '',
            'eng_grade_standard' => '',
            'invoice_info' => [
                'invoice_cd' => '',
                'invoice_no' => '',
                'invoice_dt' => '',
                'invoice_link' => '',
                'invoice_tp' => '',
                'invoice_ck_cd' => '',
                'nm' => '',
                'tax' => '',
                'invoice_tax_amt' => '',
                'sales_ent_nm' => '',
                'tax_payer' => '',
                'num' => '',
                'service_nm' => '',
            ],
            'track_info' => [
                'tracking_no' => '',
                'tracking_company' => '',
                'usr_prov' => '',
                'usr_city' => '',
                'usr_area' => '',
                'usr_addr' => '',
                'tracking_type' => '',
                'delivery_method' => '',
                'shipping_addr' => '',
                'delivery_time' => '',
            ],
        ],
    ]): PromiseInterface;
}
