patch:
  x-last-updated-at: 2023.10.12
  x-role:
    - 直连商户
    - 服务商
    - 渠道商
  tags:
    - 经营工具∙电子发票
  summary: 配置开发选项
  description: 配置开发选项(例如回调地址等) [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/apis/chapter4_8_18.shtml)
  parameters:
    - name: _
      in: body
      required: true
      schema:
        type: object
        properties:
          callback_url:
            type: string
            description: 商户回调地址
            example: https://pay.weixin.qq.com/callback
          sub_mch_code:
            type: string
            description: 子商户号
            example: '1900000109'
          show_fapiao_cell:
            type: boolean
            description: 全部账单展示开发票入口开关
            example: false
  responses:
    '200':
      schema:
        type: object
        required:
          - callback_url
        properties:
          callback_url:
            type: string
            description: 商户回调地址
            example: https://pay.weixin.qq.com/callback
          show_fapiao_cell:
            type: boolean
            description: 全部账单展示开发票入口开关
            example: false
get:
  x-last-updated-at: 2023.10.12
  x-role:
    - 直连商户
    - 服务商
    - 渠道商
  tags:
    - 经营工具∙电子发票
  summary: 查询商户配置的开发选项
  description: 查询商户配置的开发选项 [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/Offline/apis/chapter4_8_19.shtml)
  parameters: []
  responses:
    '200':
      schema:
        type: object
        required:
          - callback_url
        properties:
          callback_url:
            type: string
            description: 商户回调地址
            example: https://pay.weixin.qq.com/callback
          show_fapiao_cell:
            type: boolean
            description: 全部账单展示开发票入口开关
            example: false
