post:
  x-last-updated-at: 2020.04.09
  x-role: [直连商户, 服务商, 渠道商]
  tags:
    - 运营工具∙委托营销
  summary: 建立合作关系API
  description: 该接口主要为商户提供营销资源的授权能力，可授权给其他商户或小程序，方便商户间的互利合作。 [官方文档](https://pay.weixin.qq.com/wiki/doc/apiv3/wxpay/marketing/partnerships/chapter3_1.shtml)
  parameters:
    - name: Idempotency-Key
      in: header
      type: string
      description: 业务请求幂等值
      required: true
    - name: _
      in: body
      required: true
      schema:
        type: object
        required: [partner, authorized_data]
        properties:
          partner:
            type: object
            required: [type]
            description: 合作方信息
            properties:
              type:
                type: string
                description: 合作方类别
                enum:
                  - APPID
                  - MERCHANT
              appid:
                type: string
                description: 合作方APPID
              merchant_id:
                type: string
                description: 合作方商户ID
          authorized_data:
            type: object
            required: [business_type]
            description: 被授权数据
            properties:
              business_type:
                type: string
                description: 授权业务类别
                enum:
                  - FAVOR_STOCK
                  - BUSIFAVOR_STOCK
              stock_id:
                type: string
                description: 授权批次ID
  responses:
    200:
      schema:
        type: object
        required: [partner, authorized_data, state, build_time, create_time, update_time]
        properties:
          partner:
            type: object
            required: [type]
            description: 合作方信息
            properties:
              type:
                type: string
                description: 合作方类别
                enum:
                  - APPID
                  - MERCHANT
              appid:
                type: string
                description: 合作方APPID
              merchant_id:
                type: string
                description: 合作方商户ID
          authorized_data:
            type: object
            required: [business_type]
            description: 被授权数据
            properties:
              business_type:
                type: string
                description: 授权业务类别
                enum:
                  - FAVOR_STOCK
                  - BUSIFAVOR_STOCK
              stock_id:
                type: string
                description: 授权批次ID
          state:
            $ref: '../../../definitions/Enumerations.yaml#State'
          build_time:
            type: string
            format: rfc3339
            description: 建立合作关系时间
          create_time:
            type: string
            format: rfc3339
            description: 创建时间
          update_time:
            type: string
            format: rfc3339
            description: 更新时间
