post:
  x-api-cert-required: true
  tags:
    - APIv2∙通用
  summary: 服务商子商户开发配置新增支付目录/新增对应APPID关联
  description: 服务商给特约子商户配置支付目录；每个商户最多配置5个支付目录。[官方文档](https://pay.weixin.qq.com/wiki/doc/api/mch_bank.php?chapter=9_24_2&index=2&p=901)
  consumes:
    - application/xml
  produces:
    - application/xml
  parameters:
    - name: _
      in: body
      required: true
      schema:
        $ref: '../../../definitions/addsubdevconfig.yaml#/addsubdevconfig.request'
  responses:
    '200':
      description: ''
      schema:
        $ref: '../../../definitions/addsubdevconfig.yaml#/addsubdevconfig.response'
